FROM python:3.10-slim

WORKDIR /celery_app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["celery", "-A", "celery_conf.celery_app", "beat", "--loglevel=info", "-B", "-E"]
