version: '3.8'

services:
  tests_ylab:
    container_name: tests_ylab
    build:
      context: .
      dockerfile: Dockerfile-test
    entrypoint: sh -c "pytest tests/"
    networks:
      - ylab_test_network
    ports:
      - "8000:8000"
    depends_on:
        postgres_tests_ylab:
          condition: service_healthy

  postgres_tests_ylab:
    container_name: postgres_tests_ylab
    image: postgres:15.1-alpine
    environment:
      POSTGRES_DB: ylabtest
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      PGUSER: postgres
    expose:
      - 5432
    ports:
      - "5432:5432"
    networks:
      - ylab_test_network
    healthcheck:
      test: [ "CMD-SHELL", 'pg_isready', '-U', 'postgres', '-d', 'ylabtest' ]
      interval: 10s
      timeout: 30s
      retries: 5
      start_period: 80s


networks:
  ylab_test_network:
    name: ylab_test_network
