FROM python:3.10-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir

COPY . .

RUN rm -r tests

CMD ["uvicorn", "main:app", "--host", "0.0.0.0"]
